### ISSUE TITLE
License file COPYING wrong?

### ISSUE THREAD

**Issue by bkuhls** [notspiff/visualization.goom#3]
Hi,

the file COPYING refers to GPL v3 but src/Main.cpp mentions GPL v2 or later.
Which version is the correct one?

Regards, bkuhls

**Comment by notspiff** [comment]
Thanks for pointing this out! I screwed up somehow. The addon code is GPLv2 (goom itself is a bit fuzzy - see its COPYING file), but i take it you can use that under LGPLv2 as well. Remedied in https://github.com/wsnipex/visualization.goom/pull/5 (i'm not upstream for this addon).
